# Generated by Django 5.2.4 on 2025-07-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='requirement_log_count',
            field=models.PositiveIntegerField(default=1, help_text='How many total logs are needed to reach this level.'),
        ),
        migrations.AlterField(
            model_name='level',
            name='requirement_description',
            field=models.CharField(help_text="Human-readable rule, e.g., 'Log meditation 3 times.'", max_length=255),
        ),
    ]
