# Generated by Django 5.2.4 on 2025-07-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_display_order_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='completion_timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='notes',
        ),
    ]
